- client/src/styles/variables.scss
변수 추가 및 수정
수정된 디자인의 css 변수를 추가 수정
close #9
> [#9] 변수 추가 및 수정

- client/.eslintrc.json
- client/package-lock.json
- client/package.json
js-cookie 라이브러리 추가 및 console.log 허용
- js-cookie 라이브러리 추가
- console.log 허용
> [#20] js-cookie 라이브러리 추가

- server/.gitignore
- server/src/main/java/com/genesisairport/reservation/Response/ReservationDateResponse.java
- server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
예약가능날짜 더미 API 작성
- 예약가능날짜 API의 예시 데이터를 반환하는 코드 작성
- .gitignore 수정
- 작성 코드를 기반으로 실제 동작하는 API 작성
> [#21] 예약가능날짜 더미 API 작성

- server/src/main/java/com/genesisairport/reservation/Response/ReservationPostResponse.java
- server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
예약정보 저장 api 호출 시 더미 데이터 반환
- `/v1/reservation`으로 접근 시 api 명세에 작성한 예시 데이터를 반환하도록 구현
- DB와 연동하여 실제 동작하도록 API 구현
> [#28] 예약정보저장 api 더미 데이터 반환

- client/src/styles/styles.scss
페이지 공통 속성 추가
페이지 공통 속성 추가
- 배경색 : 흰색
- 행 방향 가운데 정렬
> style: 페이지 공통 속성 추가

- server/.gitignore
- server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
- server/src/main/java/com/genesisairport/reservation/response/ReservationPostResponse.java
- server/src/main/java/com/genesisairport/reservation/respository/RepairShopRepository.java
- server/src/main/java/com/genesisairport/reservation/respository/ReservationRepository.java
- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
예약 정보 저장 api의 구현을 명세에 맞춰 customerId도 바디에 담도록 구현함
쿠키를 기반으로 사용자 id를 관리하여 서버에서 사용자 정보에 접근하도록 변경
- querydsl에의한 변경사항 반영
- 쿠키 기반으로 현재 사용자 파악
> [#48] 예약정보저장 api 현재사용자쿠키 기반 동작

- server/src/main/java/com/genesisairport/reservation/response/ReservationPostResponse.java
- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
예약정보저장 api의 반환값을 필요에 맞게 변경
- 에약 id 제거
- 시간 정보 제거
- 고객 이름 추가
- 정비소 전화번호에대한 내용을 추가
- 데이터베이스
- 코드
> [#54] 예약정보저장 api 반환 내용 변경

- client/src/pages/ReservationComplete.js
- client/src/styles/pages/reservComp.scss
- client/src/styles/variables.scss
페이지에 파라미터 표시
- 넘겨받은 파라미터로 텍스트 표시
- 폰트 추가
- 예약 버튼 링크 추가
> [#52] 페이지에 파라미터 표시

- client/src/pages/ReservationComplete.js
- client/src/styles/pages/reservComp.scss
- client/src/styles/styles.scss
선택한 서비스가 보이도록 수정
- 예약화면 스타일 적용
- 클래스명 오류 수정
> [#63] 선택한 서비스가 보이도록 수정

- client/src/styles/variables.scss
폰트 변수 구조화 및 추가
- 폰트 변수 구조화 및 추가
- 범용 class 작성
> [#70] 폰트 변수 구조화 및 추가

- client/src/components/ProfileCard.js
- client/src/components/ReservationCard.js
- client/src/pages/Mypage.js
- client/src/styles/pages/myPage.scss
마이페이지의 예약내역 항목 퍼블리싱
- 마이페이지/내정보 content 부분 컴포넌트화
- 마이페이지/예약내역 content 부분 컴포넌트화
- 페이지 내에서 선택하여 원하는 컴포넌트를 출력
- 예약 내역의 카드 클릭 시 홈으로 route
- 2개의 페이지가 겹친다고 판단하여 마이페이지 내에서 '내정보', '예약내역' 컴포넌트를 호출하는 방식으로 구현
- 날짜 출력 양식 조정
- css classname 겹치는 부분에 대한 의존성 설정 ( ">"를 사용)
- 예약 상세 페이지로 route
> [#85] 예약내역페이지 작성

- server/src/main/java/com/genesisairport/reservation/response/UserResponse.java
- server/src/main/java/com/genesisairport/reservation/service/UserService.java
프로필 api에 email 추가
- UserService.getUserProfile에 이메일을 추가로 넣음
- Response Dto에도 email 추가
> fix: 프로필 api에 email 추가

- server/src/main/java/com/genesisairport/reservation/respository/RepairShopRepositoryImpl.java
예약 가능 여부 조회 API 로직 수정
- 기존: 첫 타임으로 예약 가능/불가능 판단
- 변경: 전체 시간에 대해 예약 가능/불가능 판단
```java
private ReservationResponse.DateInfo convertToDateInfo(List<Tuple> tuples) {
Map<String, Boolean> map = new HashMap<>();
for (Tuple t : tuples) {
Date date = t.get(0, Date.class);
String formattedDate = new SimpleDateFormat("yyyy-MM-dd").format(date);
int cnt = t.get(2, Integer.class);
int capacity = t.get(3, Integer.class);
Boolean available = cnt < capacity ? true : false;
map.computeIfAbsent(formattedDate, k -> available);
}
List<String> availableDates = new ArrayList<>();
for (Map.Entry<String, Boolean> entry : map.entrySet()) {
if (entry.getValue()) {
availableDates.add(entry.getKey());
}
}
Collections.reverse(availableDates);
return ReservationResponse.DateInfo.builder() …
```
> [#96] 예약 가능 여부 조회 API 로직 수정

- server/src/main/java/com/genesisairport/reservation/common/CommonDateFormat.java
- server/src/main/java/com/genesisairport/reservation/controller/UserController.java
- server/src/main/java/com/genesisairport/reservation/entity/Customer.java
- server/src/main/java/com/genesisairport/reservation/response/UserResponse.java
- server/src/main/java/com/genesisairport/reservation/service/UserService.java
GET user/info API 개발완료
- customer, car entity로부터 Dto 생성하여 데이터 전달
- LocalDate는 CommonDateFormat 클래스에서 String으로 변환해줌
> feat: GET user/info API 개발완료

- server/src/main/java/com/genesisairport/reservation/controller/AuthController.java
- server/src/main/java/com/genesisairport/reservation/controller/UserController.java
- server/src/main/java/com/genesisairport/reservation/request/UserRequest.java
- server/src/main/java/com/genesisairport/reservation/service/AuthService.java
- server/src/main/java/com/genesisairport/reservation/service/UserService.java
PATCH /user/info 개발완료
- 사용자 정보 업데이트 기능 개발 완료
- request에 있는 파라미터에 대해서만 update
- RequestDto 중 LoginDto -> UserDto로 변경하여 유저 관련 dto를 모아뒀습니다.
- 예외처리는 아직 하지 않았음. 예외처리 로직 개발해야 될 것 같습니다
> [#104] PATCH /user/info 개발완료

- client/src/components/ProfileCard.js
- client/src/components/ReservationCard.js
- client/src/styles/pages/myPage.scss
- server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
- server/src/main/java/com/genesisairport/reservation/respository/CarRepository.java
- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
와이어프레임에는 있지만 api 반환값에는 없는 부분을 해소하기위해
/car-list, /list api 반환값에 이미지 url 추가
마이페이지에 이미지 경로를 기반으로 출력하도록 반영
- /list api 반환값 추가 (이미지 경로)
- 마이페이지 이미지를 반환값 기반으로 출력
- 변경된 /profile api를 기반으로 내정보 페이지에서 email을 출력하도록 변경
- 애니메이션 추가
> [#101] /car-list, /list api 반환값에 이미지 경로를 추가 후 마이페이지 반영

- client/src/components/ProfileCard.js
- client/src/components/ReservationCard.js
- client/src/pages/Mypage.js
- client/src/styles/pages/myPage.scss
마이페이지 UX 향상을 위한 애니메이션 추가
- 내정보 페이지 애니메이션 추가
- 예약내역 페이지 애니메이션 추가
- 메뉴 변경 시 스크롤 상단으로 이동
- 내정보 상세 페이지 연결
- 예약 상세 페이지 연결
> [#109] 마이페이지 애니메이션 추가

- client/src/components/AirportBranch.js
- client/src/components/AnimatedComponent.js
- client/src/pages/ReservationIntro.js
- client/src/styles/pages/reservationIntro.scss
예약 인트로 페이지 수정
- 예약 버튼 클릭 시 예약 페이지로 이동
- 스크롤 애니메이션 추가
현재 공항 버튼 클릭 시 통일된 예약 페이지로 이동
-> 김포 공항 클릭 시 김포 공항 예약 페이지로, 인천 공항 클릭 시 인천 공항 페이지로 이동하는 분기 필요
> [#105] 예약 인트로 페이지 수정

- client/src/pages/Main.js
- client/src/styles/components/header.scss
- client/src/styles/pages/myPage.scss
- client/src/styles/variables.scss
기존 myPage.scss는 스타일 값을 하드코딩함
공통적으로 선언한 변수를 통해 공통 요소를 한 번에 관리할 수 있도록 함
추가1) 헤더 z-index를 100으로 설정하여 페이지의 최 상단에 표시되도록 반영
추가2) 세션 만료시간 변경
- 공통 글씨 스타일 M_18 추가
- myPage.scss 공통 요소에 변수 반영
- 페이지 타이틀 높이 변경
- 헤더 z-index 변경
- 세션 만료 시간 연장
- 폰트 변경 (소문자 추가)
- 폰트 공통요소 피그마와 동기화
> Design/#114 mypage scss 변수

- server/src/main/java/com/genesisairport/reservation/controller/TextController.java
헬스체크 전용 API 추가
-  "/" 경로로 헬스체크용 API 추가
- 기능은 없습니다.
> [#127] 헬스체크 전용 API 추가

- server/src/main/java/com/genesisairport/reservation/controller/CarController.java
- server/src/main/java/com/genesisairport/reservation/request/CarRequest.java
- server/src/main/java/com/genesisairport/reservation/service/CarService.java
- server/src/main/resources/application.yml
차량 추가 등록 API 구현
- 차량 추가 등록 요청 객체 CarRequest.CarPost DTO 구현
- CarController -> registerVehicle: CarPost DTO를 매개변수로 받아 차량을 등록하는 메서드
- CarService -> saveCar: CarPost DTO 객체를 파싱하여 car table에 저장하는 메서드
- application.yml ddl-auto 옵션 제거
- 프론트 엔드 API 연결
> [#121] 차량 추가 등록 API

- client/src/components/Modal.js
- client/src/pages/Profile.js
- client/src/styles/components/modal.scss
- client/src/styles/pages/myPage.scss
- client/src/styles/pages/profile.scss
프로필 페이지 수정
- 프로필 페이지 CSS 수정
- 프로필 모달 CSS 수정
- API 연결 완료
- `내 정보 조회` API
- `내 정보 수정` API
기존에는 전화번호만 <input> 타입이었는데, `내 정보 수정` API 명세에 따르면 이름&생일&전화번호가 수정 대상이라 나머지 항목들도 <input> 태그로 변경했습니다.
- 현재 차량 추가 API가 존재하지 않아 이 부분은 API 연결이 안 되어 있습니다.
- 차량 삭제도 프로필 페이지에서 해야할 거 같은데, UI + API 필요합니다.
- 모달 애니메이션
- input 에 대한 조건은 존재하지 않습니다.
- ex) 전화번호나 날짜 형식이 아닌 값, 다 입력하지 않았는데 '저장하기' 버튼 눌림(지금은 전에 있던 데이터가 유지됨)
> [#112] 프로필 페이지 수정

- server/src/main/java/com/genesisairport/reservation/controller/CarController.java
- server/src/main/java/com/genesisairport/reservation/service/CarService.java
차량 삭제 API 구현
- CarService -> deleteCar: 데이터베이스 car table에 저장되어있는 레코드(차량 정보)를 삭제하는 메서드
- CarController -> deleteVehicle
- PathVariable로 삭제할 carId를 받기
- HttpServletRequest 객체에서 쿠키 값을 추출 -> 해당 세션을 가진 CustomerId 찾기
- CarService의 deleteCar 메서드의 매개변수로 customerId, carId로 전달하여 삭제 로직 수행
- 차량 삭제 API 연동
> [#133] 차량 삭제 API 구현

- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
feat: 마이페이지에서 차 목록이 없으면 에러나는 현상 수정
- 리스트 형식으로 응답하는 API에서, 리스트가 비어있을 시 null이 아니라 0칸짜리 리스트로 반환하게 변경
> [#137] 마이페이지에서 차 목록이 없으면 에러나는 현상 수정

- client/src/pages/Main.js
cannot read properties of null 오류 수정
- addEventListener 등록 후 removeEventListener를 통해 등록된 이벤트를 삭제하도록 변경
```js
useEffect(() => {
document.addEventListener('DOMContentLoaded', runOnScroll);
window.addEventListener('scroll', runOnScroll);
document.addEventListener('DOMContentLoaded', animation);
return () => {
document.removeEventListener('DOMContentLoaded', runOnScroll);
window.removeEventListener('scroll', runOnScroll);
document.removeEventListener('DOMContentLoaded', animation);
};
}, []);
```
> [#140] cannot read properties of null 오류 수정

- client/src/components/ModalDate.js
- client/src/styles/pages/reservationModal.scss
- client/src/styles/styles.scss
modal-page 관련 scss파일들 복구
- 과거 modalPage.scss 내용 복구
> [#144] modal-page 관련 scss파일들 복구

- client/src/pages/Main.js
- client/src/styles/pages/main.scss
main.js 애니메이션 버그 수정
- title-area div에서 애니메이션이 동작하지 않는 이슈 발생
- useEffect 내에서 animation()과 runOnScroll() 함수를 직접 호출하는 방식으로 변경
- main.scss 파일 메인 배너 이미지 크기 조정
- main.scss 불필요한 공백 제거 및 폰트 컬러 scss 변수로 변경
```js
useEffect(() => {
animation();
runOnScroll();
}, []);
```
> [#146] main.js 애니메이션 버그 수정

- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
ReservationService.java에 필요한 의존성을 추가함
- Customer 추가
- RepairShop 추가
- Map 추가
- HashMap 추가
> [#151] ReservationService에 필요한 의존성 import

- client/src/components/ModalDate.js
- client/src/components/ModalHeader.js
- client/src/index.js
- client/src/pages/Main.js
- client/src/pages/ReservationIntro.js
- client/src/styles/pages/main.scss
- client/src/styles/pages/myPage.scss
- client/src/styles/pages/profile.scss
- client/src/styles/pages/reservationIntro.scss
- client/src/styles/pages/reservationModal.scss
- client/src/styles/styles.scss
scss 문제 있는 부분들 총 수정
- 메인 페이지 헤더 버튼 수정
- 예약하기 버튼 링크가 없는 링크로 가던 부분 수정
- 예약모달 페이지 scss 사라졌던 부분 복구
> fix: scss 문제 있는 부분들 총 수정

- client/src/components/AirportBranch.js
- client/src/components/AlertModal.js
- client/src/components/AnimatedComponent.js
- client/src/components/ModalDate.js
- client/src/components/ModalInfo.js
- client/src/components/ModalService.js
- client/src/components/ProfileCard.js
- client/src/components/ReservationCard.js
- client/src/components/reservation_detail/ReservationDetailInfo.js
- client/src/components/reservation_detail/ReservationDetailResult.js
- client/src/components/reservation_detail/ReservationDetailService.js
- client/src/components/reservation_detail/ReservationDetailStep.js
- client/src/pages/Reservation.js
- client/src/pages/ReservationComplete.js
- client/src/pages/ReservationDetail.js
- client/src/pages/ReservationModal.js
- client/src/styles/components/modal.scss
- client/src/styles/pages/reservationModal.scss
예약 페이지 간 이동 시 애니메이션, 필수 필드 미입력 시 alert 띄우기
- 예약 페이지 간 이동 시 fade-in, fade-out 애니메이션
- 다음 페이지로 이동 시 필수 필드가 미입력 돼있으면 alert 창을 띄움
- 
- 픽업 시간->픽업 시각으로 워딩 수정 
- 페이지마다 발생하던 react warning들도 대부분 처리 완료했습니다.
- image에 alt 추가 등
> [#155] 예약 페이지 간 이동 시 애니메이션, 필수 필드 미입력 시 alert 띄우기

- client/src/api/ReservationApi.js
- client/src/components/ModalDate.js
- client/src/components/ModalService.js
- client/src/pages/ReservationModal.js
- client/src/styles/pages/reservationModal.scss
- client/src/styles/variables.scss
- client/src/utils/dateUtils.js
- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
예약하기 화면에 실제 기능들 추가
- 날짜 클릭 시 이용가능 시간 API 호출
- 쿠폰번호 확인 버튼 클릭 시 input border 색 변경
- 예약하기 버튼 클릭 시 예약 API 호출
- 예약하기 API에서 쿠폰번호가 없는 경우가 처리되어 있지 않아 수정했습니다.
- 예약하기 API에서 날짜 포맷이 공용으로 정해둔 포맷과 맞지 않아 수정했습니다.
- 현재 예약완료 시 홈으로 이동하는데, 예약상세 화면이 완성되면 해당 상세 페이지로 이동하도록 변경 바랍니다.
-
> [#157] 예약하기 화면에 실제 기능들 추가

- client/src/pages/ReservationModal.js
- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
쿠폰번호 입력하지 않으면 예약 불가능하게 변경
- reservation API에서 쿠폰번호 입력 필수로 변경
- 프론트에서 예약하기 버튼 클릭 시 쿠폰번호 확인
> fix: 쿠폰번호 입력하지 않으면 예약 불가능하게 변경

- server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
예약 내역 상세 api에 차량 대표 이미지 추가
- ReservationDetail dto에 image url 추가
- ReservationService의 getReservationDetail 메서드에 차량 이미지를 찾는 로직 추가
> [#161] 예약 내역 상세 api에 차량 대표 이미지 추가

- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
> fix: 조건문의 닫는 괄호 추가

- server/src/main/java/com/genesisairport/reservation/response/ReservationResponse.java
- server/src/main/java/com/genesisairport/reservation/respository/CarRepository.java
차량 목록 api에 car id 추가
- carInfo interface api에 car id 추가
> feat: 차량 목록 api에 car id 추가

- client/src/components/Modal.js
- client/src/components/ProfileCard.js
- client/src/pages/Profile.js
프로필 차량 등록 시 모달 안 뜨던 현상 수정
- 프로필 등록 modal에 visible 클래스 추가
> [#167] 프로필 차량 등록 시 모달 안 뜨던 현상 수정

- server/src/main/java/com/genesisairport/reservation/controller/CarController.java
Session 엔티티 사용 코드를 HttpSession 사용 코드로 변경
[ 변경 전 ]
```java
sessionService.getLoggedInCustomer(request);
```
[ 변경 후 ]
```java
SessionService.getUserIdFromSession(request);
```
`getLoggedInCustomer()` 함수 존재하지 않아서 에러 발생 -> `getUserIdFromSession()` 함수 사용 코드로 변경
> [#179] Session 엔티티 사용 코드를 HttpSession 사용 코드로 변경

- server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
ArrayList 초기화
-  Reservation class, List 타입의 step 변수 초기화
> fix: ArrayList 초기화

- server/src/main/java/com/genesisairport/reservation/respository/StepRepository.java
- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
예약 완료 시 초기 진행 단계 설정
- Step 엔티티의 Repository 계층 추가
- 예약 완료 시 `step` 테이블에 `예약완료` 레코드 추가 기능 구현
- 예약 완료 시 초기
> [#182] 예약완료 초기단계 설정

- client/src/pages/Profile.js
차량 삭제 API 연동
- 'X' 버튼 클릭시에 차량이 삭제되도록 API 연동
- 취소 버튼 클릭시에 '/mypage'로 연결되도록 설정
```js
const handleDeleteCarClick = carId => {
deleteCar(carId)
.then(result => {
alert('차량이 성공적으로 삭제되었습니다.');
window.location.reload();
})
.catch(error => {
console.error('Error deleting car:', error);
});
};
```
> [#188] 차량 삭제 API 연동

- server/src/main/java/com/genesisairport/reservation/entity/Step.java
- server/src/main/java/com/genesisairport/reservation/service/ReservationService.java
Step 엔티티 타입 변경
- createDatetime, updateDatetime의 타입을 LocalDate에서 LocalDateTime으로 변경
> [#190] Step 엔티티 타입 변경

- client/src/components/Header.js
- client/src/components/reservation_detail/ReservationDetailInfo.js
- client/src/components/reservation_detail/ReservationDetailStep.js
- client/src/pages/Main.js
메인페이지에서 이동시 발생하는 style 오류 해결
- 타임아웃으로 스타일을 적용하는 부분에서 조건문으로 함수를 종료하도록 수정
> [#191] 메인페이지에서 이동시 발생하는 style 오류 해결

- client/src/api/Settings.js
- server/src/main/java/com/genesisairport/reservation/config/WebConfig.java
CORS 문제 해결
- Request 헤더의 'Access-Control-Allow-Origin' 값 변경
- 원인 : Server URL로 되어있었음
> [#202] CORS 문제 해결

- server/src/main/java/com/genesisairport/reservation/common/GeneralException.java
- server/src/main/java/com/genesisairport/reservation/common/GlobalExceptionHandler.java
- GeneralException 객체 생성
- GeneralExceptionHandler 객체 생성
- GeneralException 객체: 상태 응답 코드인 response code 필드와, 전달하고자하는 오류메시지를 담는 message 필드로 구성되어 있습니다.
- 사용법: GeneralException 예외를 발생시킬 때, 응답 코드와 원하는 메시지를 아래와 같이 작성합니다.
```java
if (userId == null) {
throw new GeneralException(ResponseCode.INTERNAL_ERROR, "로그인 유저 없음");
}
```
- GeneralExceptionHandler 객체: GeneralException 발생 감지시에, 아래와 같은 형태로 데이터를 감싸서 클라이언트에게 응답합니다.
```java
return super.handleExceptionInternal(
e,
body,
headers,
responseCode.getHttpStatus(),
webRequest);
}
```
- 응답 예시
```json
{
"success": true,
"code": 200,
"message": "Internal error - 로그인 유저 없음",
"data": null
}
```
- handleExceptionInternal 멤버
- Exception e
- DataResponseDto<Object> body = DataResponseDto.of(null, responseCode.getMessage(e));
- HttpHeaders headers
- …
> [#204] 공통 예외 처리

- server/build.gradle
- server/src/main/java/com/genesisairport/reservation/common/enums/ResponseCode.java
- server/src/main/java/com/genesisairport/reservation/common/exception/GeneralException.java
- server/src/main/java/com/genesisairport/reservation/common/model/DataResponseDto.java
- server/src/main/java/com/genesisairport/reservation/common/model/ResponseDto.java
- server/src/main/java/com/genesisairport/reservation/common/util/CommonDateFormat.java
- server/src/main/java/com/genesisairport/reservation/common/util/GlobalExceptionHandler.java
- server/src/main/java/com/genesisairport/reservation/common/util/RedisUtil.java
- server/src/main/java/com/genesisairport/reservation/config/S3Config.java
- server/src/main/java/com/genesisairport/reservation/controller/AuthController.java
- server/src/main/java/com/genesisairport/reservation/controller/CarController.java
- server/src/main/java/com/genesisairport/reservation/controller/ReservationController.java
- server/src/main/java/com/genesisairport/reservation/controller/TextController.java
- server/src/main/java/com/genesisairport/reservation/controller/UserController.java
- server/src/main/java/com/genesisairport/reservation/controller/admin/AReservationController.java
- server/src/main/java/com/genesisairport/reservation/entity/AvailableTime.java
- server/src/main/java/com/genesisairport/reservation/entity/Car.java
- server/src/main/java/com/genesisairport/reservation/entity/CarImage.java
- server/src/main/java/com/genesisairport/reservation/entity/Coupon.java
- server/src/main/java/com/genesisairport/reservation/entity/Customer.java
- server/src/main/java/com/genesisairport/reservation/entity/MaintenanceImage.java
- server/src/main/java/com/genesisairport/reservation/entity/RepairShop.java
- server/src/main/java/com/genesisairport/reservation/entity/Reservation.java
- server/src/main/java/com/genesisairport/reservation/entity/Step.java
- server/src/main/java/com/genesisairport/reservation/respository/MaintenanceImageRepository.java
- server/src/main/java/com/genesisairport/reservation/service/S3Service.java
- server/src/main/java/com/genesisairport/reservation/service/UserService.java
- server/src/main/java/com/genesisairport/reservation/service/admin/AReservationService.java
- server/src/main/java/com/genesisairport/reservation/service/admin/AdminReservationService.java
* POST /v2/admin/reservation/{id}/image API 개발
* Entity 전체적으로 DynamicInsert 어노테이션 추가
* **공통 변경 사항 - 실행 파라미터에 다음 내용 추가 요망!!**
* S3_ACCESS_KEY=(notion security 페이지에서 S3 upload IAM ID 참고)
* S3_SECRET_KEY=(notion security 페이지에서 S3 upload IAM Password 참고)
* S3_BUCKET=genesis-airport
* /v2/admin/reservation/69/image API 추가
* 이미지와 함께 요청을 보내면 s3에 이미지가 업로드되며, maintenance_image 테이블에 url 정보가 추가된다.
* 같은 이름으로 업로드하면 파일명 뒤에 (1), (2)와 같이 번호가 붙여져서 저장된다.
기본적으로 Spring Data JPA를 통해 Entity를 insert할 때, **null로 설정된 필드도 모두 쿼리에 포함된다.**
예를 들어, TestEntity에 String data, LocalDatetime createDatetime 두 개의 필드가 있다고 가정하자.
data에 "hello"만 담아서 testRepository.save(entity)를 수행하면 DB에는 다음과 같은 쿼리가 전달된다.
`INSERT INTO test_table (data, create_datetime) VALUES ("hello", null);`
이렇게 하면 DB 상에서 create_datetime의 DEFAULT 값이 …
> [#212] 정비 전후 사진 업로드 API

- admin/src/components/Button.js
- admin/src/components/SideBar.js
- admin/src/components/svg/LogoutImage.js
- admin/src/index.js
- admin/src/pages/RservationDetail.js
- admin/src/styles/components/button.scss
- admin/src/styles/components/sideBar.scss
- admin/src/styles/pages/reservationDetail.scss
- admin/src/styles/styles.scss
예약관리 상세 퍼블리싱
* 예약관리 페이지 퍼블리싱 완료
* 버튼 컴포넌트 hover effect 추가
* SideBar에 로그아웃 버튼 추가
* Button.js에서 default 함수가 여러 개인 문제도 해결했습니다.
> feat: 예약관리 상세 퍼블리싱

- server/src/main/java/com/genesisairport/reservation/common/util/CommonDateFormat.java
- server/src/main/java/com/genesisairport/reservation/controller/admin/AShopController.java
- server/src/main/java/com/genesisairport/reservation/repository/AvailableTimeRepository.java
- server/src/main/java/com/genesisairport/reservation/repository/AvailableTimeRepositoryCustom.java
- server/src/main/java/com/genesisairport/reservation/repository/AvailableTimeRepositoryImpl.java
- server/src/main/java/com/genesisairport/reservation/request/AdminRequest.java
- server/src/main/java/com/genesisairport/reservation/response/AdminResponse.java
- server/src/main/java/com/genesisairport/reservation/service/admin/AShopService.java
예약가능시간 추가, 삭제 및 조회 api를 개발했습니다.
1. request dto 추가
```java
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public static class ReservationTime {
private String shopName;
private String businessDay;
}
```
지점명과 시간 정보를 담는 dto 입니다.
2. api 요청 확인
```java
@PostMapping("/available")
public ResponseEntity<ResponseDto> addAvailableDate(@RequestBody AdminRequest.ReservationTime requestBody) {
if (requestBody.getShopName() == null) {
throw new GeneralException(ResponseCode.BAD_REQUEST, "지점명 누락");
}
if (requestBody.getBusinessDay() == null) {
throw new GeneralException(ResponseCode.BAD_REQUEST, "날짜 정보 누락");
}
return new ResponseEntity<>(ResponseDto.of(true, aShopService.addAvailableTime(requestBody)), HttpStatus.OK);
}
```
지점명이나 날짜 정보 없이 요청하는 경우 오류를 반환하도록 했습니다.
3. 예약가능시간 단일 조회 구현
```java …
```
> [#210] 예약가능시간 관련 api 개발

- server/src/main/java/com/genesisairport/reservation/common/model/PageInfo.java
- server/src/main/java/com/genesisairport/reservation/common/model/PageResponseDto.java
- server/src/main/java/com/genesisairport/reservation/controller/admin/AAccountController.java
- server/src/main/java/com/genesisairport/reservation/entity/Admin.java
- server/src/main/java/com/genesisairport/reservation/repository/AdminRepository.java
- server/src/main/java/com/genesisairport/reservation/repository/AdminRepositoryCustom.java
- server/src/main/java/com/genesisairport/reservation/repository/AdminRepositoryImpl.java
- server/src/main/java/com/genesisairport/reservation/request/AdminRequest.java
- server/src/main/java/com/genesisairport/reservation/response/AdminResponse.java
- server/src/main/java/com/genesisairport/reservation/service/admin/AAccountService.java
- Admin에 Querydsl 세팅
- RepositoryCustom, RepositoryImpl 구현
- 고급 검색
- 검색어 입력
- 속성 정렬
- Pagination
- Page, Pageable 적용
- QuerydslRepositorySupport
- Admin에 Querydsl 세팅
- RepositoryCustom, RepositoryImpl 구현
- 고급 검색
- 검색어 입력
> RequestBody의 검색어를 기반으로 조건문 작성합니다.
```java
private BooleanBuilder getBuilderForWhereClause(String adminId, String adminName, String phoneNumber) {
BooleanBuilder builderForWhereClause = new BooleanBuilder();
if (!Strings.isEmpty(adminId)) { // null 이거나 "" 가 아니면
builderForWhereClause.and(admin.adminId.eq(adminId));
}
if (!Strings.isEmpty(adminName)) {
builderForWhereClause.and(admin.adminName.eq(adminName));
}
if (!Strings.isEmpty(phoneNumber)) {
builderForWhereClause.and(admin.phoneNumber.eq(phoneNumber));
}
return builderForWhereClause;
}
```
- 속성 정렬
> RequestBody의 정렬 …
> [#221] 관리자 계정 조회 api 개발

- admin/src/api/ReservationApi.js
- admin/src/pages/ReservationList.js
관리자 | 예약 관리 페이지 - 페이지네이션 적용
- 예약 내역 검색 API 수정 필요합니다.
> feat : 관리자 예약 페이지에 페이지네이션 적용
